package org.openmrs.module.eptsreports.reporting.utils;

public enum CommunityType {
  ALL,
  NORMAL,
  OUT_OF_TIME,
  FARMAC_PRIVATE_PHARMACY,
  COMMUNITY_DISPENSE_PROVIDER,
  COMMUNITY_DISPENSE_APE,
  DAILY_MOBILE_BRIGADES,
  NIGHT_MOBILE_BRIGADES,
  DAILY_MOBILE_CLINICS,
  NIGHT_MOBILE_CLINICS,
  MOBILE_BRIGADES,
  MOBILE_CLINICS,
}
